### ISSUE TITLE
Switch to use fsnotify/fsnotify?

### ISSUE THREAD

**Issue by kevinburke** [jmhodges/justrun#10]
This project relies on howeyc/fsnotify, which includes this note:

> There is a fork being actively developed with a new API in preparation for the Go Standard Library: github.com/go-fsnotify/fsnotify

From that project: 

> fsnotify utilizes golang.org/x/sys rather than syscall from the standard library.

Currently uses kqueue for event watching on Macs, though, not FSEvents. I'm not sure whether that would make any difference on the "out of FD's" problem.

**Comment by jmhodges** [comment]
This would be nice to do. I have no idea if it will improve things either. I'm out of time at the moment, but maybe it would be easy for someone to do.

**Comment by jmhodges** [comment]
I have a weird tingling that there was something about it that was weird but I can't remember what that was. It might have just been a temporary problem.

Ah, maybe it was a lack of OS X support in its past?

**Comment by jmhodges** [comment]
Done. Lmk how it works for you

**Comment by kevinburke** [comment]
Thanks, will let you know!
